name: "Test backend systems"

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  tests:
    timeout-minutes: 15
    runs-on: [ docker, builder ]
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Server and Test with Newman
        working-directory: ./backend
        run: npm run test:system
